package objetos;

public class Armaduras {
	
	public enum Tela {
		
		ATUENDO_COMUN,
		ATUENDO_DE_CAZADOR,
		ATUENDO_DE_PESCADOR,
		ATUENDO_DE_HERRERO,
		ATUENDO_DE_EXPLORADOR,
		ATUENDO_DE_GRANJERO,
		ATUENDO_DE_TABERNERO,
		ATUENDO_DE_COCINERO,
		ATUENDO_DE_NOBLE,
		ATUENDO_DE_MARINERO,
		ATUENDO_DE_LADRON,
		ATUENDO_DE_ASESINO,
		ATUENDO_DE_MONJE,
		ATUENDO_DE_SACERDOTE,
		ROPA_BUENA,
		TUNICA,
		TUNICA_DE_MAGO,
		TUNICA_DE_CEREMONIA,
		ROPA_RAIDA,
		VESTIDO,
		ARMADURA_DE_TELA,
		ARMADURA_DE_CUERO,
		
	}
	
	public enum Rigida {
		
		ARMADURA_MORGATHI,
		ARMADURA_MJORVEGR,
		ARMADURA_DE_HUESOS,
		ARMADURA_DE_HIERRO,
		ARMADURA_DE_ACERO,
		ARMADURA_DE_PLACAS,
		ARMADURA_FJELLFOLK,
		COTA_DE_MALLA,
		ARMADURA_DE_INQUISIDOR,
		ARMADURA_DE_PALADIN,
		ARMADURA_REAL,
		ARMADURA_DE_GUARDIAN,
		ARMADURA_LEGENDARIA,
		
	}

}
